# Use separate configs for local and remote sessions
# https://github.com/samoshkin/tmux-config/blob/95efd543846a27cd2127496b74fd4f4da94f4a31/tmux/tmux.conf#L355

if-shell 'test -n "$SSH_CLIENT"' \
    'source-file ~/.config/tmux/tmux.remote.conf'
if-shell '! test -n "$SSH_CLIENT"' \
    'source-file ~/.config/tmux/tmux.local.conf'

source-file ~/.config/tmux/tmux.common.conf
