#!/usr/bin/env bash

# counts the number of arguments passed to the script, -eq 1 check if it equals 1.
# Get the pd name

# Different resource prefixes for the platform and ais clusters
projects=$(oc projects)

if echo "$projects" | grep platform; then
    resource="appwrapper"
else
    resource="pods"
fi
header="NAME                                STATUS      QUOTA RESERVED   RESOURCES DEPLOYED   UNHEALTHY   AGE"
job_name=$(oc get $resource | rg ${1:-goon} | fzf --header="$header" | awk '{print $1}')

if [[ -z $job_name ]]; then
	exit 0
fi

oc describe $resource $job_name
