#!/usr/bin/env bash

# counts the number of arguments passed to the script, -eq 1 check if it equals 1.
# Get the pd name

# Different resource prefixes for the platform and ais clusters
projects=$(oc projects)

resource="pod"
header="NAME                                      READY   STATUS              RESTARTS   AGE     IP              NODE                                  NOMINATED NODE   READINESS GATES"
pod_names=$(oc get pods -o wide | rg  ${1:-goon} | fzf -m --header="$header" | awk '{print $1}')

if [[ -z $pod_names ]]; then
	exit 0
fi


if [ $(echo "$pod_names" | wc -w) -gt 1 ]; then
    for pod in $pod_names; do tmux new-window "oc describe $resource $pod_name"; done
else
    oc describe $resource $pod_names
fi
