#!/usr/bin/env bash

# counts the number of arguments passed to the script, -eq 1 check if it equals 1.
# Get the pd name

# Different resource prefixes for the platform and ais clusters
projects=$(oc projects)

resource="pod"
header="NAME                                      READY   STATUS              RESTARTS   AGE     IP              NODE                                  NOMINATED NODE   READINESS GATES"
pod_name=$(oc get pods -o wide | rg  ${1:-goon} | fzf  --header="$header" | awk '{print $1}')

if [[ -z $pod_name ]]; then
	exit 0
fi

oc describe $resource $pod_name
