#!/usr/bin/env bash


# Different resource prefixes for the platform and ais clusters
projects=$(oc projects)

if echo "$projects" | grep platform; then
    resource="appwrapper"
else
    resource="pods"
fi


header="NAME                                         STATUS      QUOTA RESERVED   RESOURCES DEPLOYED   UNHEALTHY"
job_names=$(oc get $resource | rg ${1:-goon} | fzf -m --bind ctrl-a:select-all --header="$header" | awk '{print $1}')

if [[ -z $job_names ]]; then
    exit 0
fi

echo -e "Delete these jobs? [y/N]\n${job_names}"
read response
case "$response" in
    [yY][eE][sS]|[yY])
        DELETE=1
        ;;
    *)
        DELETE=0
        ;;
esac


if [ $DELETE = "1" ]; then
    for name in $job_names; do oc delete $resource $name; done
else
    echo "Delete aborted!"
fi
