#!/usr/bin/env bash

get_pod_status() {
    pod_status=$(oc get pods -o wide | rg  $1 | awk '{print $3}')
    echo $pod_status
}


# Print out the pod name, whether or not we C-c to cancel
trap handleInt SIGINT


function handleInt {
    echo ""
    echo "Logs: $pod_name"
    exit 0
}

# The logs disconnect often, so just infinite loop until we get a Ctrl-C or the pod stops running.

if [ "$(get_pod_status $1)" = "Completed" ]; then
        oc logs $1 -f --prefix
fi

while true
do
    case "$(get_pod_status $1)" in
        "Running")
            oc logs $1 -f --prefix
            # oc logs $pod_name -f --timestamps --prefix
            ;;
        "Pending"|"ContainerCreating"|"Init"*|"Resetting"|"PodInitializing"|"Suspended"|"Suspending")
            # oc logs $1 -f --prefix
            oc logs $1 -f --prefix || sleep 5
            # oc logs $pod_name -f --timestamps --prefix
            ;;
        *)
        echo "$1 in state $(get_pod_status $1)! Exiting."
        printf "Press Enter to continue..." && read dummy
        exit 0
    esac
done

