#!/usr/bin/env bash

format="%.12i %.50j %.8T %.12M %.6D %R"
header=$(squeue --me --format="$format" | head -1)

job_ids=$(squeue --me --noheader --format="$format" | fzf -m --bind ctrl-a:select-all --header="$header" | awk '{print $1}')

if [[ -z $job_ids ]]; then
    exit 0
fi

echo -e "Delete these jobs? [y/N]\n${job_ids}"
read -r response
case "$response" in
    [yY][eE][sS]|[yY])
        scancel $job_ids
        ;;
    *)
        echo "Delete aborted!"
        ;;
esac
