#!/usr/bin/env bash

format="%.12i %.50j %.8T %.12M %.6D %R"
header=$(squeue --me --format="$format" | head -1)

job_id=$(squeue --me --noheader --format="$format" | fzf --header="$header" | awk '{print $1}')

if [[ -z $job_id ]]; then
    exit 0
fi

scontrol show job "$job_id"
