#!/usr/bin/env bash

selected=$(tmux list-sessions -F "#S" | fzf -m \
  --header="Tab: select for deletion | Enter: switch | Ctrl-X: kill selected" \
  --bind 'enter:transform:[[ $FZF_SELECT_COUNT -eq 0 ]] && echo accept || echo "change-header:Multi-select is for deletion only -- press Ctrl-X to kill, or Tab to deselect"' \
  --bind 'ctrl-x:execute(
      echo "Kill these sessions? [y/N]"
      printf "%s\n" {+}
      read -r response
      case "$response" in
          [yY][eE][sS]|[yY])
              for name in {+}; do tmux kill-session -t "$name"; done
              ;;
          *)
              echo "Delete aborted!"
              ;;
      esac
  )+reload(tmux list-sessions -F "#S")+clear-multi+change-header(Tab: select for deletion | Enter: switch | Ctrl-X: kill selected)')

[[ -z "$selected" ]] && exit 0

clients=$(tmux list-clients)
if [[ -z $TMUX ]] || [[ -z $clients ]]; then
  tmux attach-session -t "$selected"
else
  tmux switch-client -t "$selected"
fi
