local comments = require("agent-comments.comments")

local function scratch(lines, name)
	local b = vim.api.nvim_create_buf(false, true)
	vim.api.nvim_buf_set_lines(b, 0, -1, false, lines)
	if name then
		vim.api.nvim_buf_set_name(b, name)
	end
	return b
end

T.test("comments: add + get returns live data", function()
	comments.clear()
	local b = scratch({ "l1", "l2", "l3", "l4" }, "/tmp/hn-a.lua")
	local id = comments.add(b, 2, 3, "fix this")
	local c = comments.get(id)
	T.eq({ c.start_line, c.end_line, c.text }, { 2, 3, "fix this" })
	T.ok(c.file:match("hn%-a%.lua$"))
end)

T.test("comments: range tracks edits above it", function()
	comments.clear()
	local b = scratch({ "l1", "l2", "l3", "l4" })
	local id = comments.add(b, 3, 4, "x")
	vim.api.nvim_buf_set_lines(b, 0, 0, false, { "new0", "new1" }) -- insert 2 lines at top
	local c = comments.get(id)
	T.eq({ c.start_line, c.end_line }, { 5, 6 })
end)

T.test("comments: snippet returns current covered lines", function()
	comments.clear()
	local b = scratch({ "a", "b", "c" })
	local id = comments.add(b, 2, 3, "x")
	vim.api.nvim_buf_set_lines(b, 1, 2, false, { "B-EDITED" })
	T.eq(comments.snippet(id), { "B-EDITED", "c" })
end)

T.test("comments: exclusive endpoint excludes following line after final-line expansion", function()
	comments.clear()
	local b = scratch({ "l1", "l2", "l3", "l4" })
	local id = comments.add(b, 2, 3, "x")
	vim.api.nvim_buf_set_lines(b, 2, 3, false, { "l3a", "l3b" })
	T.eq(comments.snippet(id), { "l2", "l3a", "l3b" })
end)

T.test("comments: edit, delete, list ordering", function()
	comments.clear()
	local b1 = scratch({ "x" }, "/tmp/hn-b.lua")
	local b2 = scratch({ "x", "y" }, "/tmp/hn-a2.lua")
	local i1 = comments.add(b1, 1, 1, "one")
	local i2 = comments.add(b2, 2, 2, "two")
	local i3 = comments.add(b2, 1, 1, "three")
	T.ok(comments.edit(i1, "one-edited"))
	T.eq(comments.get(i1).text, "one-edited")
	-- sorted by file then start_line: hn-a2:1, hn-a2:2, hn-b:1
	local l = comments.list()
	T.eq({ l[1].id, l[2].id, l[3].id }, { i3, i2, i1 })
	T.ok(comments.delete(i2))
	T.eq(#comments.list(), 2)
	T.eq(comments.get(i2), nil)
end)

T.test("comments: list drops wiped buffers", function()
	comments.clear()
	local b = scratch({ "x" })
	comments.add(b, 1, 1, "gone")
	vim.api.nvim_buf_delete(b, { force = true })
	T.eq(comments.list(), {})
end)

T.test("comments: a draft is anchored but stays out of the list until it has text", function()
	comments.clear()
	local b = scratch({ "l1", "l2", "l3", "l4" })
	local id = comments.add(b, 3, 4, nil)
	local c = comments.get(id)
	T.eq({ c.start_line, c.end_line }, { 3, 4 })
	T.eq(c.text, nil, "a draft carries no text yet")
	T.eq(comments.snippet(id), { "l3", "l4" }, "a draft still resolves, to seed an editor")
	T.eq(comments.list(), {}, "a draft must not reach the prompt or the comment list")
	T.ok(comments.edit(id, "written"))
	local l = comments.list()
	T.eq(#l, 1)
	T.eq({ l[1].id, l[1].text }, { id, "written" })
end)

T.test("comments: a draft's range tracks edits made before it is committed", function()
	comments.clear()
	local b = scratch({ "l1", "l2", "l3", "l4" })
	local id = comments.add(b, 3, 4, nil)
	vim.api.nvim_buf_set_lines(b, 0, 0, false, { "new0", "new1" })
	comments.edit(id, "written late")
	local c = comments.list()[1]
	T.eq({ c.start_line, c.end_line, c.text }, { 5, 6, "written late" })
	T.eq(comments.snippet(id), { "l3", "l4" }, "and still quotes the lines it was anchored to")
end)

T.test("comments: a committed comment reports the unsaved state it froze", function()
	comments.clear()
	local clean = scratch({ "x" }, "/tmp/hn-frozen-unsaved.lua")
	local frozen_unsaved = comments.add(clean, 1, 1, nil)
	comments.edit(frozen_unsaved, "/tmp/hn-frozen-unsaved.lua:1-1 [unsaved]\n   1 | x\n")
	T.ok(not vim.bo[clean].modified, "the buffer this was frozen from is now clean")
	T.eq(comments.get(frozen_unsaved).modified, true, "the snapshot keeps its [unsaved] marker")

	local dirty = vim.api.nvim_create_buf(true, false)
	vim.api.nvim_buf_set_lines(dirty, 0, -1, false, { "y" })
	vim.api.nvim_buf_set_name(dirty, "/tmp/hn-frozen-saved.lua")
	local frozen_saved = comments.add(dirty, 1, 1, nil)
	comments.edit(frozen_saved, "/tmp/hn-frozen-saved.lua:1-1\n   1 | y\n")
	T.ok(vim.bo[dirty].modified, "the buffer has unwritten changes")
	T.eq(comments.get(frozen_saved).modified, false, "the snapshot was rendered without one")
end)

T.test("comments: a draft re-reads its buffer's unsaved state", function()
	comments.clear()
	local b = vim.api.nvim_create_buf(true, false)
	vim.api.nvim_buf_set_lines(b, 0, -1, false, { "x" })
	vim.api.nvim_buf_set_name(b, "/tmp/hn-live-unsaved.lua")
	local id = comments.add(b, 1, 1, nil)
	T.eq(comments.get(id).modified, true, "the seed is rendered from the live buffer")
	vim.bo[b].modified = false
	T.eq(comments.get(id).modified, false)
end)
